ci: Add slack notifications on phylum daily analysis

diff --git a/.github/workflows/phylum-daily-analysis.yaml b/.github/workflows/phylum-daily-analysis.yaml
--- a/.github/workflows/phylum-daily-analysis.yaml
+++ b/.github/workflows/phylum-daily-analysis.yaml
@@ -1,9 +1,18 @@
 name: Daily Analysis Phylum
 
+# on:
+#   schedule:
+#     # Runs at 13:00 UTC every day
+#     - cron: '0 13 * * *'
+
 on:
-  schedule:
-    # Runs at 14:00 UTC every day
-    - cron: '0 14 * * *'
+  push:
+    branches:
+      - DO-2613
+env:
+  PHYLUM_PROJECT_ID: 851c8804-e9f6-423c-be8e-c529d22f4abd
+  PHYLUM_GROUP_NAME: Protocol
+  PHYLUM_NAME: radixdlt-scrypto
 jobs:
   analyze_branch_phylum:
     name: Analyze dependencies with Phylum
@@ -37,10 +46,38 @@ jobs:
       - name: Run Phylum Analysis
         env: 
           PHYLUM_API_KEY: ${{ secrets.PHYLUM_API_KEY }}         
-        run: phylum analyze --quiet --label ${{ matrix.branch }}_branch_daily_schedule > /dev/null 2>&1 || 
-          if [ $? -eq 100 ]; then 
-            echo "Phylum Analysis returned exit code 100, but continuing."; 
+        run: phylum analyze --quiet --label ${{ matrix.branch }}_branch_daily_schedule > /dev/null 2>&1 || exit_code=$?
+          if [ $exit_code -eq 100 ]; then 
+            echo "Phylum Analysis returned exit code 100, but continuing.";
+            echo "phylum_analyze_status=failure" >> $GITHUB_ENV 
             exit 0; 
+          elif [ $exit_code -eq 0 ]; then
+            echo "phylum_analyze_status=success" >> $GITHUB_ENV
+            exit 0;
           else 
+            echo "phylum_analyze_status=failure" >> $GITHUB_ENV 
             exit $?; 
           fi
+      - name: Analysis Status Failure notification
+        if: always()
+        uses: RDXWorks-actions/notify-slack-action@master
+        with:
+          status: ${{ env.phylum_analyze_status }}
+          notify_when: 'failure'
+          notification_title: ':clock3: Phylum Scheduled Daily Analysis:'
+          message_format: 'Automatic phylum analysis has found vulnerabilities on ${{ env.PHYLUM_NAME }} in ${{ matrix.branch }} branch:boom:'
+          footer: "Linked Repository <{repo_url}|{repo}> | <https://app.phylum.io/projects/${{ env.PHYLUM_PROJECT_ID }}?label=${{ matrix.branch }}_branch_daily_schedule&group=${{ env.PHYLUM_GROUP_NAME }}|View Inform> "
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PHYLUM_PROTOCOL_TEAM_WEBHOOK }}
+
+      - name: Analysis Status Success notification
+        if: always()
+        uses: RDXWorks-actions/notify-slack-action@master
+        with:
+          status: ${{ env.phylum_analyze_status }}
+          notify_when: 'success'
+          notification_title: ':clock3: Phylum Scheduled Daily Analysis:'
+          message_format: 'Automatic phylum analysis has not found vulnerabilities on ${{ env.PHYLUM_NAME }} in ${{ matrix.branch }} branch :rocket: '
+          footer: "Linked Repository <{repo_url}|{repo}> | <https://app.phylum.io/projects/${{ env.PHYLUM_PROJECT_ID }}?label=${{ matrix.branch }}_branch_daily_schedule&group=${{ env.PHYLUM_GROUP_NAME }}|View Inform> "
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PHYLUM_PROTOCOL_TEAM_WEBHOOK }}
